### ISSUE TITLE
評価画面

### ISSUE THREAD

**Issue by shimizuyuta** [shimizuyuta/tornado_team2#5]
![image](https://user-images.githubusercontent.com/58338829/184927188-385d0875-cbee-4852-8e04-dff5af2d6ead.png)

**Comment by nmy998244353** [comment]
![スクリーンショット 2022-08-27 113831](https://user-images.githubusercontent.com/80047713/187011071-b323bb6d-f68a-4b81-8876-57e392a583cd.png)
